In [1]:
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt

In [2]:
input = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = 3
Dx = np.eye(n*n)
# upper-right off diagonal terms are -1
for i in range(n*n-1):
    Dx[i, i+1] = -1
Dy = np.eye(n*n)
for i in range(n*n-1):
    j = (i + n) % (n*n)
    Dy[i, j] = -1
D = np.vstack((Dx, Dy))
print(D)
D_input = D @ input.flatten()
print(D_input[:9].reshape(3,3))
print(D_input[9:].reshape(3,3))    
        



[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1.  9.]]
[[-3. -3. -3.]
 [-3. -3. -3.]
 [ 6.  6.  9.]]
